// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eckohtoprkgolyjdiown.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVja29odG9wcmtnb2x5amRpb3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjUyNTcsImV4cCI6MjA2MDEwMTI1N30.-pEsBnwaXjqnuspEa8arMrxfRa4m9yMkJQuBAFY5VII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);